name: dotnet package

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies (dotnet restore)
        run: dotnet restore

      - name: Build It
        run: dotnet build --configuration Release --no-restore

      - name: Test It
        run: dotnet test --no-restore

      - name: Publish It (dotnet publish)
        run: dotnet publish Library.Client --configuration Release --runtime win10-x64 --self-contained false

      - name: Upload to Github
        uses: actions/upload-artifact@v3
        with:
          name: Library.Client-packaged
          path: ./Library.Client/bin/Release/net6.0/win10-x64/publish/