name: dotnet package

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0.x']

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies (dotnet restore)
        run: dotnet restore
      - name: Build It
        run: dotnet build --configuration Release --no-restore
      - name: Test It
        run: dotnet test --no-restore
      - name: Publish It (dotnet publish)
        run: dotnet publish Library.Client --configuration Release
      - name: Upload to Github
        uses: actions/upload-artifact@v2
        with:
          name: Library.Client-packaged
          path: ./Library.Client/bin/Release/net5.0/publish/